---
title: "Three (Groups of) Blind Mice" 
subtitle: "Familial Clusters of Cataract Development in Irradiated Mice"
author: "Alyssa Allsop and Amira Burns"
date: "`r Sys.Date()`"
output: 
  ioslides_presentation: 
    widescreen: true
    fontsize: 10
---

```{r setup, include=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```  


## Introduction
  
- Research Questions:   
    + Are mice in some families more likely to develop more severe cataracts?
- Experimental Design:  
    + 1820 genetically heterogeneous mice from 48 unique families were randomly assigned, with equal family weights, to three treatment groups: Gamma radiation, HZE radiation, and unirradiated control. The simplified dataset records symptoms at time of death for mice of Age $\ge$ 552 days, for a total sample size of 1169.   
    + **Response**: Cataracts Status, either 0 or 1. Where 1 indicates the presence of cataracts that are of clinical concern.  
    + **Primary predictors under consideration**: Treatment, Family  
    + **Covariates**: Sex, Weight, Coat Color, Body Condition Score, Age, Myeloid Leukemia, Harderian Tumor, PreT Lymphoma


## Summary Tables & Plots 






## Final Model {.smaller}
\vspace{}
$Y_{ij} \sim Bernoulli(p)\\log(\frac{p}{1-p}) = \beta_0 + \beta_1*Unirradiated_i*F_i + \beta_2*Gamma_i*F_i +  \beta_3*HZE*F_i + 
\\\beta_4*Unirradiated_i*M_i +  \beta_5*Gamma_i*M_i +  \beta_6*HZE_i*M_i +
[v_{j} + \epsilon_{ij}] \\ i = 1,...,1169 \: \mbox{mice} \\ j = 1,...,47 \: \mbox{families} \\ \mbox{and} \: v_j \sim N(0, \tau)$
\vspace{}
- Bayesian approach with non-informative priors
\vspace{}
\[
\begin{aligned}
\beta_0 &\sim N(0, 0.001)\\
\beta_1 &\sim N(0, 0.001)\\
\beta_2 &\sim N(0, 0.001)\\
\beta_3 &\sim N(0, 0.001)\\
\beta_4 &\sim N(0, 0.001)\\
\beta_5 &\sim N(0, 0.001)\\
\tau &\sim Gamma(0.001, 0.001) \mbox{ where}\ \sigma^2 = 1/\tau\\
\end{aligned}
\]


  
## Results  

## Results cont.
  

## Conclusions
- Our frequentist model shows the difference in cataract development among treatment groups is much larger among male rats
- Overall, the HZE group had the highest development of cataracts, followed by the Gamma group and then the unirradiated rats.
- Limitations?  

## References {.smaller}
Agresti, A (2013). *Categorical Data Analysis* (Third Edition). John Wiley & Sons.  
  
Chernyavskiy, P., Edmondson, E. F., Weil, M. M., & Little, M. P. (2017). *High-energy particle beam and gamma radiation exposure, familial relatedness and cancer in mice.* British journal of cancer, 117(1), 41–50. https://doi.org/10.1038/bjc.2017.141  
  
Gelman, A., Carlin, J., Stern, H., Dunson, D., Vehtari, A., Rubin, D. (2014). *Bayesian Data Analysis* (Third Edition). CRC Press.  
  
Roback, P., Legler, J. (2021). *Beyond Multiple Linear Regression. Applied Generalized Linear Models and Multilevel Models in R* (Second Edition). CRC Press. Online version: https://bookdown.org/roback/bookdown-BeyondMLR/  
  
DiMaggio, C., Albert, J., Spiegelhalter, D., Best, N., Gelman, A., Carstensen, B., Guerrin, L., Jensen, S. (2015) *Bayesian Analysis for Epidemiologists III: Regression Modeling.* Center for Injury Epidemiology and Prevention at Columbia University.  http://www.columbia.edu/~cjd11/charles_dimaggio/DIRE/styled-4/styled-11/code-8/#bayesian-regression-modeling-with-bugs-or-jags

  
# Any Questions?  
